name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:8
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version "16.x"
      - run: 



